### ISSUE TITLE
Is it possible to highlight more then one feature on map at the same time

### ISSUE THREAD

**Issue by bozzwin** [tangrams/explorer#9]
I am wondering if it possible highlight more than feature on map. I would like to create editor for map to allow users paint all type attribute of map. Could you give me some tips and suggestions?

**Comment by meetar** [comment]
That's exactly what this explorer tool is doing! … but with some limitations.

This tool has two ways to draw any feature. The first is with the plain "non-matching" style, when a feature doesn't match the filters set in the interface, and the second is with the "matching" style, which is used when a feature does match the filters. The map is redrawn when the filters change, and the effect is that the matching features are drawn more prominently.

However, there isn't a simple built-in feature for changing the style of arbitrary selections of features, but you could do something a bit like this tool is doing if you had a way to uniquely identify features, such as an ID value. So in your interface code you could add or remove a selected feature's ID to a group of "highlighted" features as desired.
